spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 219846710491-giic5jrj4lq1qj6ci8li0veupnnru361.apps.googleusercontent.com
            clientSecret: 4w5AcSE6p3gyAZdl61ySIs-T
            redirectUri: "http://localhost:8081/login/oauth2/code/google?role=user"
            scope:
              - email
              - profile
          kakao:
            clientId: 846bf6762aa129317f201ab1042760b9
            clientSecret: OYq6fP1VXf2IhqmeupEGnltWuPpWpYRu
            clientAuthenticationMethod: POST
            clientName: Kakao
            redirectUri: "http://localhost:8081/login/oauth2/code/kakao?role=user"
            authorizationGrantType: authorization_code
            scope:
              - account_email
              - profile
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id